---
name: Build and Publish (Stable Release)
kind: pipeline
type: docker
trigger:
  branch:
    - stable
steps:
  - name: build
    image: ubuntu
    environment:
      # PKGBUILD variables
      release_type: stable
      # Other stuff
      DEBIAN_FRONTEND: noninteractive
    commands:
      - scripts/build.sh

  - name: publish
    image: ubuntu
    environment:
      nexus_repository_password:
        from_secret: nexus_repository_password
      DEBIAN_FRONTEND: noninteractive
    commands:
      - scripts/publish.sh

---
name: Build and Publish (Alpha Release)
kind: pipeline
type: docker
trigger:
  branch:
    - alpha
steps:
  - name: build
    image: ubuntu
    environment:
      # PKGBUILD variables
      release_type: alpha
      # Other stuff
      DEBIAN_FRONTEND: noninteractive
    commands:
      - scripts/build.sh

  - name: publish
    image: ubuntu
    environment:
      nexus_repository_password:
        from_secret: nexus_repository_password
      DEBIAN_FRONTEND: noninteractive
    commands:
      - scripts/publish.sh
