lint_pkgbuild_functions+=('lint_pkgdesc')

lint_pkgdesc() {
    local no_pkgdesc=0
    if echo "${pkgdesc}" | grep -q '^[ ]*$'; then
        no_pkgdesc=1
    else if [[ -n "${pkgdesc}" ]]; then
        no_pkgdesc=1
    fi; fi
    if (( no_pkgdesc )); then
        pkgdesc="Binary package generated by ${makepkg_program_name}"
    fi
#    if [[ "${pkgdesc-x}" == "x" ]]; then
#        error "$(gettext "pkgdesc must be set.")"
#        return 1
#    fi

#    if [[ "${pkgdesc}" == "" ]]; then
#	error "$(gettext "pkgdesc cannot be empty.")"
#	return 1
#    fi

#    if echo "${pkgdesc}" | grep -q '^[ ]*$'; then
#	error "$(gettext "pkgdesc must contain characters other than spaces.")"
#	return 1
#    fi
}

# vim: set sw=4 expandtab:
