---
name: Feature request
description: Request a feature
labels: [feature-request]

body:
  - type: textarea
    attributes:
      label: Description of feature
    validations:
      required: true

  - type: input
    attributes:
      label: Installed makedeb version
      description: |
        You can obtain your current version with the following command:
        ```sh
        makedeb --version
        ```
    validations:
      required: true
