#!/bin/bash
_makedeb() {
	cur=${COMP_WORDS[COMP_CWORD]}
	prev=${COMP_WORDS[COMP_CWORD-1]}

	case "$prev" in
		-h|--help)
			return
			;;

		-A|--ignore-arch)
			return
			;;

		-d|--no-deps)
			return
			;;

		-F|--file)
			COMPREPLY=( $( compgen -W "$(\ls -1aA .)" -- $cur ) )
			return
			;;

		-g|--gen-integ)
			return
			;;

		-H|--field)
			return
			;;
		-i|--install)
			return
			;;
		-V|--version)
			return
			;;
		-r|--rm-deps)
			return
			;;
		-s|--sync-deps)
			return
			;;
		--print-control)
			return
			;;
		--print-srcinfo)
			return
			;;
		--skip-pgp-check)
			return
			;;
		--verbose)
			return
			;;
		--as-deps)
			return
			;;
	esac

	case "$cur" in
		-*)
			COMPREPLY=('--ignore-arch --no-deps --file --gen-integ --help --help --field --install --version --rm-deps --sync-deps --print-control --print-srcinfo --skip-pgp-check --verbose --as-deps --no-confirm')
			;;

		*)
			COMPREPLY=('-A -d -F -g -h -H -i -V -r -s')
			;;
	esac
}
complete -o filenames -o bashdefault -F _makedeb makedeb
